name: frontend-github-actions
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - develop
env:
  PNPM_VERSION: 8.7.6

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use pnpm cache
      uses: actions/cache@v3
      id: pnpm_cache
      with:
        path: |
          /usr/local/bin/pnpm
          /usr/local/lib/node_modules/pnpm
        key: ${{ runner.os }}-pnpm-${{ env.PNPM_VERSION }}

    - name: Install globals
      if: ${{ steps.pnpm_cache.outputs.cache-hit != 'true' }}
      run: npm i -g pnpm@${{ env.PNPM_VERSION }}

    - name: Use Node modules cache
      uses: actions/cache@v3
      id: packages_cache
      with:
        path: node_modules/*
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: ${{ steps.packages_cache.outputs.cache-hit != 'true' }}
      run: pnpm i

    - name: Run test
      run: ls && pnpm test

  run-component-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install globals
      run: npm i -g pnpm@v8.7.6

    - name: Install dependencies
      run: pnpm i

  build-nextjs-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install globals
      run: npm i -g pnpm@v8.7.6

    - name: Install dependencies
      run: pnpm i

    - name: Build Next.js app
      run: pnpm build
