name: frontend-github-actions
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - develop
env:
  PNPM_VERSION: 8.7.6

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    outputs:
      pnpm-cache-key: ${{ steps.cache-keys.outputs.pnpm }}
      packages-cache-key: ${{ steps.cache-keys.outputs.packages }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Calculate cache keys
      id: cache-keys
      run: |
        echo "packages=${{ runner.os }}-node-${{ matrix.node-version }}-nextjs-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

    - name: Use Node modules cache
      if: ${{ !startsWith(github.head_ref, 'dependabot') }}
      uses: actions/cache@v3
      id: packages-cache
      with:
        path: "**/node_modules"
        key: ${{ steps.cache-keys.outputs.packages }}

    - name: Install dependencies
      if: ${{ steps.packages-cache.outputs.cache-hit != 'true' }}
      run: pnpm i

  run-unit-test:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Use Node modules cache
      uses: actions/cache/restore@v3
      id: packages-cache
      with:
        path: "**/node_modules"
        key: ${{ needs.setup.outputs.packages-cache-key }}

    - name: Install dependencies
      if: ${{ steps.packages-cache.outputs.cache-hit != 'true' }}
      run: pnpm i

    - name: Run test
      run: pnpm test

  build-nextjs-app:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Use Node modules cache
      uses: actions/cache/restore@v3
      with:
        path: "**/node_modules"
        key: ${{ needs.setup.outputs.packages-cache-key }}

    - name: Install dependencies
      if: ${{ steps.packages-cache.outputs.cache-hit != 'true' }}
      run: pnpm i

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
    - name: Build Next.js app
      run: pnpm build
