name: frontend-github-actions
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - develop
env:
  PNPM_VERSION: 8.7.6

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    outputs:
      pnpm-cache-key: ${{ steps.cache-keys.outputs.pnpm }}
      packages-cache-key: ${{ steps.cache-keys.outputs.packages }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Calculate cache keys
      id: cache-keys
      run: |
        echo "::set-output name=pnpm::$(echo "${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ env.PNPM_VERSION }}")"
        echo "::set-output name=packages::$(echo "${{ runner.os }}-node-${{ matrix.node-version }}-nextjs-${{ hashFiles('**/package-lock.json') }}")"

    - name: Use pnpm cache
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: ~/.npm/pnpm-global
        key: ${{ steps.packages-cache.outputs.pnpm }}

    - name: Install globals
      if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
      run: npm i -g pnpm@${{ env.PNPM_VERSION }}

    - name: Use Node modules cache
      uses: actions/cache@v3
      id: packages-cache
      with:
        path: ~/.npm
        key: ${{ steps.cache-keys.outputs.packages }}

    - name: Install dependencies
      if: ${{ steps.packages-cache.outputs.cache-hit != 'true' }}
      run: pnpm i

  run-unit-test:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Tokyo"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug outputs
      run: |
        echo ${{ needs.setup.outputs.pnpm-cache-key }}
        echo ${{ needs.setup.outputs.packages-cache-key }}
    - name: Use pnpm cache
      uses: actions/cache@v3
      id: pnpm_cache
      with:
        path: ~/.npm/pnpm-global
        key: ${{ needs.setup.outputs.pnpm-cache-key }}

    - name: Use Node modules cache
      uses: actions/cache@v3
      id: packages_cache
      with:
        path: ~/.npm
        key: ${{ needs.setup.outputs.packages-cache-key }}

    - name: Run test
      run: ls && pnpm test

  build-nextjs-app:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use pnpm cache
      uses: actions/cache@v3
      id: pnpm_cache
      with:
        path: ~/.npm/pnpm-global
        key: ${{ needs.setup.outputs.pnpm-cache-key }}

    - name: Use Node modules cache
      uses: actions/cache@v3
      id: packages_cache
      with:
        path: ~/.npm
        key: ${{ needs.setup.outputs.packages-cache-key }}

    - name: Build Next.js app
      run: pnpm build
